### ISSUE TITLE
GMPU Source Code

### ISSUE THREAD

**Issue by vliberio** [alatnet/gmpu#1]
Hello,

Sorry to bother you. I really love using your publishing utility. I tried to add you on Steam (as Agent of Corruption), but you denied the request. I know you don't want to work on this lovely piece of software, but my friends and I avidly use it and I would love to add a few bits of functionality for convenience. Your source code doesn't seem to be anywhere I can find on the internet. The Facepunch thread is also missing. Would you consider uploading the code to GitHub so I could fork the code so I could add a few useful things (and potentially make a pull request if you think they aren't shit)? I apologize for the inconvenience, but I would really appreciate it.

Thanks,
Vince

**Comment by alatnet** [comment]
Huh. so that's what that was.
Yea, i'll upload the source.
Dont think i can compile it as it uses netbeans to deal with the gui design and netbeans generally doesnt like newer versions of java atm.

**Comment by vliberio** [comment]
Thank you, I really appreciate it.
